# Generated by Django 4.1.3 on 2026-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('gest_count', models.IntegerField()),
                ('reservation_time', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
